### ISSUE TITLE
你好，能写一个ftp+nginx的dockerfile吗

### ISSUE THREAD

**Issue by 2738671** [mritd/docker-compose#1]
我想利用ftp上传附件到nginx的代理目录，实现网址下载的功能。要求能映射ftp和nginx的配置文件。但是我不知道怎么写。

**Comment by mritd** [comment]
能具体描述一下你的需求么？比如具体的 ftp 工具，nginx 的具体配置情况等

**Comment by 2738671** [comment]
1,yum install vsftpd
2, useradd -d /home/ftpuser  ftpuser #增加用户test，并制定ftpuser用户的主目录为/home/ftpuser
3, passwd ftpuser #为test设置密码
4, 修改：/etc/vsftpd/vsftpd.conf




pasv_promiscuous=YES  #取消ip验证
pasv_enable=YES              #开启被动连接
pasv_min_port=8091       #被动端口范围
pasv_max_port=8092


5，yum install nginx
6，vi  etc/nginx/nginx.conf 
把user项目 改成test









以上是我在linux端完成的2个插件的安装和配置，现在想通过dockerfilie来实现，但是我写不来。
就是通过ftp上传附件，并通过nginx代码来浏览





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mritd"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 上午10:28
收件人:&nbsp;"mritd/docker-compose"<docker-compose@noreply.github.com&gt;;
抄送:&nbsp;"越心人"<2738671@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mritd/docker-compose] 你好，能写一个ftp+nginx的dockerfile吗 (#1)




能具体描述一下你的需求么？比如具体的 ftp 工具，nginx 的具体配置情况等
